### ISSUE TITLE
Missing file gopi/cmd/input/input_tester.go

### ISSUE THREAD

**Issue by petergloor** [djthorpe/gopi#14]
Line 37 in https://github.com/djthorpe/gopi/blob/master/cmd/build_rpi.sh contains the following statement:

    input/input_tester.go

However, there is no file gopi/cmd/input/input_tester.go.

**Comment by djthorpe** [comment]
Apologies I was temporarily moving the input source code into a separate repository. I've now fixed this in v1.0.9 and the input code is now in a separate repository, here:

https://github.com/djthorpe/gopi-input

The build scripts work on linux, rpi and darwin [Mac]. Please let me know if I can help further.
