### ISSUE TITLE
Github pages are not available

### ISSUE THREAD

**Issue by jdevelop** [djthorpe/gopi#64]
http://djthorpe.github.io/gopi/ - doesn't seem to work, returns 404.

**Comment by djthorpe** [comment]
Hi yes I moved this to http://gopi.mutablelogic.com/ but forgot to update the links. I will do that and thanks for your report.

**Comment by djthorpe** [comment]
I have updated V1 and merged this with master. I am actually developing new V2 code and documentation which is in the V2 branch, but this isn't yet passing tests. You can view the V2 documentation here: https://gopi.mutablelogic.com/v/v2/
